<?php
function require(string $path):

require_once(__DIR__ . '/vendor/autoload.php'); // Include the Stripe PHP library

\Stripe\Stripe::setApiKey('sk_test_51NKPxoGiKfvGONAwTvT9BtjOO4DUT1vqATpalegZ5JASKQam7jOb51PXJrj5aepQDj91deB8NwSWJQFbD29tzEFH00X05mIBBY'); // Set your Stripe API key

// Handle the payment form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $token = $_POST['stripeToken']; // Retrieve the token generated by Stripe.js
    $amount = 1000; // Amount in cedis (e.g., ¢10.00)

    try {
        // Create a charge using the Stripe API
        $charge = \Stripe\Charge::create([
            'amount' => $amount,
            'currency' => 'ghs',
            'description' => 'Payment description',
            'source' => $token,
        ]);

        // Payment successful
        echo 'Payment successful! Charge ID: ' . $charge->id;
    } catch (\Stripe\Exception\CardException $e) {
        // Payment failed
        echo 'Payment failed: ' . $e->getMessage();
    }
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Payment Form</title>
    <script src="https://js.stripe.com/v3/"></script> <!-- Include Stripe.js -->
</head>
<body>
    <h1>Payment Form</h1>
    <form action="payment_form.php" method="post"> <!-- Update the form action to match the filename -->
        <input type="text" name="cardholder_name" placeholder="Cardholder Name" required>
        <div id="card-element"></div> <!-- Stripe.js will create the card input field here -->
        <button type="submit">Pay Now</button>
    </form>

    <script>
        // Create a Stripe client
        var stripe = Stripe('pk_test_51NKPxoGiKfvGONAwjVWQ7ePZtmzH1HaCroIsmyzqscj8RWsjhGfB8ZUtDdNu2X9MZH7lFsb9jZiArLY4oPXaQmMv00U2MBBoH0');

        // Create an instance of Elements
        var elements = stripe.elements();

        // Create a card element and mount it to the card element container
        var card = elements.create('card');
        card.mount('#card-element');
    </script>
</body>
</html>
